# Generated by Django 5.1 on 2024-08-15 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Options_RMMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Option_RMMCQ',
                'verbose_name_plural': 'Options_RMMCQ',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Options_RO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Option_RO',
                'verbose_name_plural': 'Options_RO',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Question_RMMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('passage', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question_RMMCQ',
                'verbose_name_plural': 'Questions_RMMCQ',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question_RO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('answer', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question_RO',
                'verbose_name_plural': 'Questions_RO',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question_SST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question_SST',
                'verbose_name_plural': 'Questions_SST',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.AddField(
            model_name='options_rmmcq',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_rmmcq', to='question.question_rmmcq'),
        ),
        migrations.AddField(
            model_name='options_ro',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_ro', to='question.question_ro'),
        ),
        migrations.AddField(
            model_name='audio',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='question.question_sst'),
        ),
    ]
