# Generated by Django 5.1 on 2024-08-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_audio_options_rmmcq_options_ro_question_rmmcq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options_rmmcq',
            old_name='option',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='options_ro',
            old_name='option',
            new_name='title',
        ),
    ]
