# Generated by Django 5.1 on 2024-08-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
