# Generated by Django 5.1 on 2024-08-15 04:21

import question.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_rename_option_options_rmmcq_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to=question.models.upload_location),
        ),
    ]
