# Generated by Django 5.1 on 2024-08-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(),
        ),
    ]
