# Generated by Django 5.1 on 2024-08-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_answer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='object_id',
            new_name='question_id',
        ),
    ]
